{{ $config := .Values.lodview.configFile }}
{{- if and $config.enabled (not $config.existingConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lodview.configFile.configMapName" . }}
data:
  "conf.ttl": |-
    {{- include "lodview.configFile.prefixes" . | nindent 4 }}

    <> a conf:Configuration;

    conf:homeUrl <{{- include "lodview.configFile.homepage" . -}}>;

    {{ range $predicate, $value := .Values.lodview.configFile.config -}}
      conf:{{ $predicate -}} {{- include "lodview.configFile.renderRDFObject" (dict "obj" $value "context" $) | nindent 6 }}
    {{ end -}}.
{{- end }}