{{ $config := .Values.lodview }}
{{- if and $config.enabled (not $config.existingConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lodview.configMapName" . }}
data:
  "config.ttl": |-
    {{- include "lodview.prefixes" . | nindent 4 }}

    <> a conf:Configuration;

    conf:homeUrl <{{- include "lodview.homepage" . -}}>;

    {{ range $predicate, $value := .Values.lodview.config -}}
      conf:{{ $predicate -}} {{- include "lodview.renderRDFObject" (dict "obj" $value "context" $) | nindent 6 }}
    {{ end -}}.
{{- end }}