{{- if .Values.initdb.enabled }}
apiVersion: v1
kind: {{ .Values.initdb.kind }}
metadata:
  name: {{ include "sparql.initdb.configMapName" . }}
data:
  {{- range $key, $val := .Values.initdb.data }}
  {{ $key | quote }}: {{ $val  | quote }}
  {{- end }}
{{- end }}