
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sparql.secretName" . }}
type: Opaque
data:
  DAVPassword: {{ .Values.DAVPassword | default (randAlphaNum 32) | b64enc | quote }}
  DBAPassword: {{ .Values.DBAPassword | default (randAlphaNum 32) | b64enc | quote }}

