
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sparql.secretName" . }}
type: Opaque
data:
  dav_password: {{ .Values.DAVPassword | default (randAlphaNum 32) | b64enc | quote }}
  dba_password: {{ .Values.DBAPassword | default (randAlphaNum 32) | b64enc | quote }}

