{{- $fullName := include "sparql.fullname" . }}
apiVersion: v1
kind: Secret
metadata:
  name: secrets-{{ $fullName }}
type: Opaque
data:
  DAVPassword: {{ .Values.DAVPassword | b64enc | quote }}
  DBAPassword: {{ .Values.DBAPassword | b64enc | quote }}

