__author__ = 'elhassouni'

'''
The prefix file
'''

base = '@base'
base_uri = 'http://www.southgreen.fr/agrold/'
base_ns = 'agrold:'
pr = '@prefix'
rdf = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#'
rdf_ns = 'rdf:'
rdfs = 'http://www.w3.org/2000/01/rdf-schema#'
rdfs_ns = 'rdfs:'
owl = 'http://www.w3.org/2002/07/owl#'
owl_ns = 'owl:'
xsd = 'http://www.w3.org/2001/XMLSchema#'
xsd_ns = 'xsd:'
owl_uri = 'http://www.w3.org/2002/07/owl#'
owl_ns = 'owl:'
obo_uri = 'http://purl.obolibrary.org/obo/'
obo_ns = 'obo:'
base_vocab_uri = 'http://www.southgreen.fr/agrold/vocabulary/'
base_vocab_ns = 'agrold_vocabulary:'
chromosome_uri = 'http://www.southgreen.fr/agrold/chromosome/'
chromosome_ns = 'chromosome:'
resource = 'http://www.southgreen.fr/agrold/resource/'
res_ns = 'agrold_schema:'
