from django import forms
import datetime

'''
pub_date = models.DateTimeField('date published')
author = models.CharField("author", max_length=25)
title = models.CharField("title", max_length=140)
text = models.TextField("text")
'''
class BlogForm(forms.Form):
    author = forms.CharField(label="Author", max_length=25)
    title = forms.CharField(label="Title", max_length=140)
    text = forms.CharField(label="Text",
        widget=forms.Textarea(
            attrs={'placeholder': 'Write blog here'}
        )
    )
# TODO: have to figure out how to remove autogenerated labels from forms
# because they're hellah annoying
