name: Test Helm chart

on:
  workflow_call:

run-name: Test Helm Chart

jobs:
  job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        helm-charts: [agrold-javaweb, virtuoso]

    steps:
      - uses: actions/checkout@v3

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Helm Check Action
        uses: hopisaurus/helm-check-action@v0.1.0
        env:
          CHART_LOCATION: ./agrold-javaweb/charts/${{ matrix.helm-charts }}
          CHART_VALUES: ./agrold-javaweb/charts/${{ matrix.helm-charts }}/values.yaml
        with:
          chart-location: ./agrold-javaweb/charts/${{ matrix.helm-charts }}
          chart-values: ./agrold-javaweb/charts/${{ matrix.helm-charts }}/values.yaml
